services:

  # Banco de dados do customer-management
  customer-management-db:
    image: postgres:16
    container_name: customer-management-db
    environment:
      POSTGRES_DB: customer_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - customer_management_data:/var/lib/postgresql/data

  # Eureka Server
  eureka-server:
    build: ./infra/eureka-server
    ports:
      - "8761:8761"

  # API Gateway
  api-gateway:
    build: ./infra/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  # Microserviço customer-management
  customer-management:
    build: ./customer-management
    ports:
      - "8081:8081"
    depends_on:
      - customer-management-db
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  customer_management_data:
