name: CI e Deploy para VPS Hostinger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rodar testes do microserviço booking
        working-directory: ./booking
        run: ./mvnw test

      - name: Rodar testes do microserviço customer-management
        working-directory: ./customer-management
        run: ./mvnw test

      - name: Rodar testes do microserviço establishment-management
        working-directory: ./establishment-management
        run: ./mvnw test

#      - name: Rodar testes do microserviço professional-management
#        working-directory: ./professional-management
#        run: ./mvnw test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy com SSH
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SOURCE: "./"
          ARGS: "-rltgoDzvO --delete"
